# SSL certificates for development
# $ mkcert build-maksym-aliatin235.local www.build-maksym-aliatin235.local
#
# Start composition:
# $ docker-compose -f docker-compose-build.yml up -d
#
# For MacOS users (development only)
# $ docker-sync-stack start
version: '3.7'
services:
  php-apache:
    container_name: maksym-aliatin235.local-build
    # EXECUTION_ENVIRONMENT - 'development' or 'production'
    image: defaultvalue/php:7.3-${EXECUTION_ENVIRONMENT}
    # In case you need your own Dockerfile. Dockerfile example:
    # ARG EXECUTION_ENVIRONMENT
    # FROM defaultvalue/php:7.3-${EXECUTION_ENVIRONMENT}
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#      args:
#        - EXECUTION_ENVIRONMENT=${EXECUTION_ENVIRONMENT}
    user: docker:docker
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always
    labels:
      - traefik.enable=true
      # HTTP
      - traefik.http.routers.maksym-aliatin235-local-build-http.rule=Host(`build-maksym-aliatin235.local`,`www.build-maksym-aliatin235.local`)
      - traefik.http.routers.maksym-aliatin235-local-build-http.entrypoints=http
      - traefik.http.routers.maksym-aliatin235-local-build-http.service=maksym-aliatin235-local-build-http
      - traefik.http.services.maksym-aliatin235-local-build-http.loadbalancer.server.port=80
      - traefik.http.services.maksym-aliatin235-local-build-http.loadbalancer.server.scheme=http
      # HTTPS
      - traefik.http.routers.maksym-aliatin235-local-build-https.rule=Host(`build-maksym-aliatin235.local`,`www.build-maksym-aliatin235.local`)
      - traefik.http.routers.maksym-aliatin235-local-build-https.entrypoints=https
      - traefik.http.routers.maksym-aliatin235-local-build-https.tls=true
      - traefik.http.routers.maksym-aliatin235-local-build-https.service=maksym-aliatin235-local-build-https
      - traefik.http.services.maksym-aliatin235-local-build-https.loadbalancer.server.port=443
      - traefik.http.services.maksym-aliatin235-local-build-https.loadbalancer.server.scheme=https
      # Develop with extension that allows setting livereload host and port - https://github.com/lokcito/livereload-extensions
      - traefik.http.routers.maksym-aliatin235-local-build-livereload-https.rule=Host(`build-maksym-aliatin235.local`,`www.build-maksym-aliatin235.local`)
      - traefik.http.routers.maksym-aliatin235-local-build-livereload-https.entrypoints=livereload-https
      - traefik.http.routers.maksym-aliatin235-local-build-livereload-https.tls=true
      - traefik.http.routers.maksym-aliatin235-local-build-livereload-https.service=maksym-aliatin235-local-build-livereload-https
      - traefik.http.services.maksym-aliatin235-local-build-livereload-https.loadbalancer.server.port=35729
      - traefik.http.services.maksym-aliatin235-local-build-livereload-https.loadbalancer.server.scheme=http
      - traefik.http.routers.maksym-aliatin235-local-build-livereload-http.rule=Host(`build-maksym-aliatin235.local`,`www.build-maksym-aliatin235.local`)
      - traefik.http.routers.maksym-aliatin235-local-build-livereload-http.entrypoints=livereload-http
      - traefik.http.routers.maksym-aliatin235-local-build-livereload-http.service=maksym-aliatin235-local-build-livereload-http
      - traefik.http.services.maksym-aliatin235-local-build-livereload-http.loadbalancer.server.port=35729
      - traefik.http.services.maksym-aliatin235-local-build-livereload-http.loadbalancer.server.scheme=http
    # Must add extra_hosts to be written to /etc/hosts - otherwise containerized application can not curl itself
    extra_hosts:
      - "build-maksym-aliatin235.local www.build-maksym-aliatin235.local:127.0.0.1"
      # Required for xDebug on Linux hosts till docker.host.internal is not available by default - https://github.com/docker/libnetwork/pull/2348/files
      - "host.docker.internal:172.17.0.1"
#    links:
#      - memcached
#      - redis
#      - elasticsearch
    external_links:
      - mysql57:mysql
      - mailhog
    network_mode: bridge
    environment:
      # Must be set to some of the domains for xdebug to work. Should have server configured in
      # Preferences > Language and Frameworks > PHP > Servers
      # Or just run the project with the same domain and debug enabled in the browser
      - PHP_IDE_CONFIG=serverName=build-maksym-aliatin235.local
      # Go is required to catch emails with Mailhog and mhsendmail (Sendmail replacement)
      - ADDITIONAL_PATH=/usr/local/go/bin
    volumes:
      - .:/var/www/html
      - ${SSL_CERTIFICATES_DIR}:/certs
      - ./docker/virtual-host-build.conf:/etc/apache2/sites-enabled/virtual-host.conf
      # IMPORTANT! The below configuration is for Mac only to enable Docker Sync Stack. Don't commit!
      #- maksym-aliatin235-local-build-sync:/var/www/html:nocopy

# IMPORTANT! The below volumes configuration is for Mac only to enable Docker Sync Stack. Don't commit!
#volumes:
#  maksym-aliatin235-local-build-sync:
#    external: true

#  redis:
#    image: redis:latest
#    network_mode: bridge
#    labels:
#      - traefik.enable=false
#    restart: always

#  memcached:
#    image: 'memcached:1.5'
#    network_mode: bridge
#    labels:
#      - traefik.enable=false
#    restart: always

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
#    environment:
#      - network.host=0.0.0.0
#      - http.host=0.0.0.0
#      - transport.host=127.0.0.1
#      - xpack.security.enabled=false
#      - indices.query.bool.max_clause_count=10240
#      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    restart: always
#    network_mode: bridge